os: linux
arch: amd64
dist: bionic
language: go
go:
- "1.14.x"
env:
  global:
  - ARGOCD_OPERATOR_IMAGE_BUILDER=docker
  - GO111MODULE=on
cache:
  directories:
  - $GOCACHE
  - $GOPATH/pkg/mod
before_install:
  - git clone https://github.com/operator-framework/operator-sdk $GOPATH/src/github.com/operator-framework/operator-sdk
  - cd $GOPATH/src/github.com/operator-framework/operator-sdk
  - git checkout v0.19.4
  - make tidy
  - make install
  - cd $GOPATH/src/github.com/argoproj-labs/argocd-operator
script: bash hack/build.sh
branches:
  only: # safelist
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
